### ISSUE TITLE
Ability to export records to csv from Fit File Explorer app

### ISSUE THREAD

**Issue by randy3739** [roznet/connectstats#53]
Would love the capability to export all columns from records to a csv file

**Comment by roznet** [comment]
It actually has/had the capability, if you right click on a list of field you have an export to csv context menu... BUT as of the last version 2.0 it does not work because when I submitted the app to apple they rejected it on basis my app is readonly of documents... I forgot to mention to them the app needs write permission to save the csv files... 

So no code changes necessary, I need to resubmit the app to apple with the extra permission. I'll do that

**Comment by randy3739** [comment]
Fantastic Brice. I really like the tool for machine learning research I’m doing.  It makes it easy to preview files before diving deeper into the data.  I was hoping I could avoid making the change myself and thanks to you I can.

Thanks again,

Randy

**Comment by roznet** [comment]
I would love to discuss idea on using machine learning on the app if you are open to it... I have a few thoughts but never got around to it. A topic I am quite interested in... That's also part of why I had build fitfileexplorer and the csv export to create files easier to import into Jupiter...

**Comment by randy3739** [comment]
Happy to discuss ideas, it’s very exciting how ML is evolving.

Thanks
